[package]
name = "pixels_engine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.11.5"
image = "0.25.5"
pixels = "0.14.0"
winit = "0.28.6"
